apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feature-maven-us-east-1b
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
